/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Salim Balçık (https://sketchfab.com/salimrg099)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-orange-platform-island-6af7afc031ec4c55a1606453b7fc0350
Title: The Orange Platform - Island
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import platform from '../assets/3d/platform.glb';
import { a } from "@react-spring/three";

const Platform = (props) => {
    const { nodes, materials } = useGLTF(platform);
    const platformRef = useRef();
    return (
        <a.group ref={platformRef} {...props}>
            <group
                position={[-1579.256, 638.137, -750.537]}
                rotation={[-1.488, -0.051, 0.498]}
                scale={129.472}
            >
                <mesh
                    geometry={nodes.Cube004_palm_0.geometry}
                    material={materials.palm}
                />
                <mesh
                    geometry={nodes.Plane013_palm_0.geometry}
                    material={materials.palm}
                    position={[-0.025, 0, -0.097]}
                    rotation={[0.007, 0.617, 0.898]}
                />
            </group>
            <group
                position={[-1333.851, 569.758, -345.546]}
                rotation={[-1.277, 0.008, 1.375]}
                scale={246.651}
            >
                <mesh
                    geometry={nodes.Cube005_palm_0.geometry}
                    material={materials.palm}
                />
                <mesh


                    geometry={nodes.Plane014_palm_0.geometry}
                    material={materials.palm}
                    position={[-0.017, 0, -0.067]}
                    rotation={[0.007, 0.617, 0.898]}
                />
            </group>
            <group
                position={[-1727.732, 698.618, -325.682]}
                rotation={[-1.655, 0.047, -2.601]}
                scale={129.472}
            >
                <mesh


                    geometry={nodes.Cube006_palm_0.geometry}
                    material={materials.palm}
                />
                <mesh


                    geometry={nodes.Plane015_palm_0.geometry}
                    material={materials.palm}
                    position={[-0.025, 0, -0.097]}
                    rotation={[0.007, 0.617, 0.898]}
                />
            </group>
            <group
                position={[-804.066, 606.615, 1369.569]}
                rotation={[-1.656, 0.282, -3.066]}
                scale={246.651}
            >
                <mesh


                    geometry={nodes.Cube001_palm_0.geometry}
                    material={materials.palm}
                />
                <mesh


                    geometry={nodes.Plane001_palm_0.geometry}
                    material={materials.palm}
                    position={[-0.017, 0, -0.067]}
                    rotation={[0.007, 0.617, 0.898]}
                />
            </group>
            <group
                position={[-1549.457, 284.218, -1309.99]}
                rotation={[-1.503, 0.167, 2.562]}
                scale={155.038}
            >
                <mesh


                    geometry={nodes.Cube002_palm_0.geometry}
                    material={materials.palm}
                />
                <mesh


                    geometry={nodes.Plane003_palm_0.geometry}
                    material={materials.palm}
                    position={[-0.017, 0, -0.067]}
                    rotation={[0.007, 0.617, 0.898]}
                />
            </group>
            <group
                position={[-1250.238, 508.513, -1671.807]}
                rotation={[-1.557, -0.18, -0.117]}
                scale={234.134}
            >
                <mesh


                    geometry={nodes.Cube007_palm_0.geometry}
                    material={materials.palm}
                />
                <mesh


                    geometry={nodes.Plane005_palm_0.geometry}
                    material={materials.palm}
                    position={[-0.017, 0, -0.067]}
                    rotation={[0.007, 0.617, 0.898]}
                />
            </group>
            <group
                position={[-1203.744, 491.767, 1324.617]}
                rotation={[-1.633, -0.169, -0.549]}
                scale={187.668}
            >
                <mesh


                    geometry={nodes.Cube014_palm_0.geometry}
                    material={materials.palm}
                />
                <mesh


                    geometry={nodes.Plane006_palm_0.geometry}
                    material={materials.palm}
                    position={[-0.017, 0, -0.067]}
                    rotation={[0.007, 0.617, 0.898]}
                />
            </group>
            <group
                position={[-1516.291, 699.619, 1453.661]}
                rotation={[-1.392, 0.027, 1.528]}
                scale={247.122}
            >
                <mesh


                    geometry={nodes.Cube015_palm_0.geometry}
                    material={materials.palm}
                />
                <mesh


                    geometry={nodes.Plane007_palm_0.geometry}
                    material={materials.palm}
                    position={[-0.017, 0, -0.067]}
                    rotation={[0.007, 0.617, 0.898]}
                />
            </group>
            <mesh


                geometry={nodes.Cube_palm_0.geometry}
                material={materials.palm}
                position={[-671.906, 392.269, -1517.183]}
                rotation={[-1.545, -0.093, -0.247]}
                scale={100}
            />
            <mesh


                geometry={nodes.Circle006_iskele_0.geometry}
                material={materials.iskele}
                position={[-692.31, 67.173, -171.55]}
                rotation={[-1.515, -0.05, -2.84]}
                scale={100}
            />
            <mesh


                geometry={nodes.Plane021_iskele_0.geometry}
                material={materials.iskele}
                position={[-466.458, -70.933, -219.407]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh


                geometry={nodes.Plane008_iskele_0.geometry}
                material={materials.iskele}
                position={[455.723, -257.915, -984.131]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={100}
            />
            <mesh


                geometry={nodes.lamp_objeler_0.geometry}
                material={materials.objeler}
                position={[-341.848, 105.286, -455.471]}
                rotation={[-Math.PI / 2, 0, -0.94]}
                scale={100}
            />
            <mesh


                geometry={nodes.kutu_objeler_0.geometry}
                material={materials.objeler}
                position={[-328.622, -11.343, -476.292]}
                rotation={[-Math.PI / 2, 0, 1.139]}
                scale={100}
            />
            <mesh


                geometry={nodes.kafes_objeler_0.geometry}
                material={materials.objeler}
                position={[-334.426, 39.137, -433.107]}
                rotation={[-Math.PI / 2, 0, 2.894]}
                scale={100}
            />
            <mesh


                geometry={nodes.varil001_objeler_0.geometry}
                material={materials.objeler}
                position={[-1726.084, 299.344, 978.202]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh


                geometry={nodes.varil002_objeler_0.geometry}
                material={materials.objeler}
                position={[-1835.456, 299.344, 917.181]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh


                geometry={nodes.kutu001_objeler_0.geometry}
                material={materials.objeler}
                position={[-507.188, -11.343, -119.672]}
                rotation={[-Math.PI / 2, 0, 0.184]}
                scale={100}
            />
            <mesh


                geometry={nodes.kutu002_objeler_0.geometry}
                material={materials.objeler}
                position={[-539.364, 73.647, -151.026]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh


                geometry={nodes.kutu003_objeler_0.geometry}
                material={materials.objeler}
                position={[-553.783, -11.343, -204.629]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh


                geometry={nodes.kutu004_objeler_0.geometry}
                material={materials.objeler}
                position={[-596.459, -11.343, -119.672]}
                rotation={[-Math.PI / 2, 0, 0.083]}
                scale={100}
            />
            <mesh


                geometry={nodes.varil008_objeler_0.geometry}
                material={materials.objeler}
                position={[-926.275, 301.842, 857.118]}
                rotation={[-Math.PI / 2, 0, 2.517]}
                scale={100}
            />
            <mesh


                geometry={nodes.varil009_objeler_0.geometry}
                material={materials.objeler}
                position={[-912.478, 301.842, 771.505]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh


                geometry={nodes.varil010_objeler_0.geometry}
                material={materials.objeler}
                position={[-998.084, 302.654, 714.802]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh


                geometry={nodes.varil011_objeler_0.geometry}
                material={materials.objeler}
                position={[-1072.285, 348.868, 820.308]}
                rotation={[0, 1.359, 0]}
                scale={100}
            />
            <mesh


                geometry={nodes.kutu005_objeler_0.geometry}
                material={materials.objeler}
                position={[-967.896, -175.302, -989.082]}
                rotation={[-Math.PI / 2, 0, 0.184]}
                scale={100}
            />
            <mesh


                geometry={nodes.kutu006_objeler_0.geometry}
                material={materials.objeler}
                position={[-975.124, -158.025, -892.226]}
                rotation={[-1.74, -0.052, -0.055]}
                scale={100}
            />
            <mesh


                geometry={nodes.kafes001_objeler_0.geometry}
                material={materials.objeler}
                position={[-1703.24, 317.447, 70.746]}
                rotation={[-Math.PI / 2, 0, 1.7]}
                scale={100}
            />
            <mesh


                geometry={nodes.kafes002_objeler_0.geometry}
                material={materials.objeler}
                position={[-1703.24, 369.625, 70.746]}
                rotation={[-Math.PI / 2, 0, 1.7]}
                scale={100}
            />
            <mesh


                geometry={nodes.kafes003_objeler_0.geometry}
                material={materials.objeler}
                position={[-1703.24, 422.005, 70.746]}
                rotation={[-Math.PI / 2, 0, 1.7]}
                scale={100}
            />
            <mesh


                geometry={nodes.Cube008_rock3_0.geometry}
                material={materials.rock3}
                position={[-1007.161, -130.439, -1494.882]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh


                geometry={nodes.Cube003_rock1_0.geometry}
                material={materials.rock1}
                position={[-1399.246, -96.193, -148.532]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={105.119}
            />
            <mesh


                geometry={nodes.Plane002_rock2_0.geometry}
                material={materials.rock2}
                position={[-2013.989, 103.242, -436.054]}
                rotation={[-Math.PI / 2, 0, -2.217]}
                scale={120.425}
            />
            <mesh
                geometry={nodes.Cube009_rock1_0.geometry}
                material={materials.rock1}
                position={[-414.221, -436.699, 1325.232]}
                rotation={[-1.637, 0.139, -0.88]}
                scale={157.699}
            />
            <mesh
                geometry={nodes.Cube010_rock4_0.geometry}
                material={materials.rock4}
                position={[-2141.842, 6.309, -57.583]}
                rotation={[-Math.PI / 2, 0, -2.239]}
                scale={283.235}
            />
            <mesh
                geometry={nodes.Plane012_rock2_0.geometry}
                material={materials.rock2}
                position={[-254.244, -441.05, 1526.474]}
                rotation={[-Math.PI / 2, 0, 3.013]}
                scale={208.681}
            />
            <mesh
                geometry={nodes.Cube013_rock3_0.geometry}
                material={materials.rock3}
                position={[-584.809, -176.073, 1706.638]}
                rotation={[-Math.PI / 2, 0, -2.763]}
                scale={150.301}
            />
            <mesh
                geometry={nodes.Cube018_rock1_0.geometry}
                material={materials.rock1}
                position={[-588.997, -248.731, -1625.287]}
                rotation={[-1.489, 0.076, 1.881]}
                scale={134.333}
            />
            <mesh
                geometry={nodes.Cube019_rock1_0.geometry}
                material={materials.rock1}
                position={[-2131.564, -87.867, 605.871]}
                rotation={[-1.594, -0.384, 2.753]}
                scale={259.796}
            />
            <mesh
                geometry={nodes.Cube011_rock3_0.geometry}
                material={materials.rock3}
                position={[-1363.481, -124.196, -943.086]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={202.018}
            />
            <mesh
                geometry={nodes.Cube012_rock1_0.geometry}
                material={materials.rock1}
                position={[-2021.314, -224.629, 1080.717]}
                rotation={[-1.443, -0.19, -0.698]}
                scale={220.097}
            />
            <mesh
                geometry={nodes.Plane004_rock2_0.geometry}
                material={materials.rock2}
                position={[-1770.279, -130.843, 1336.435]}
                rotation={[-1.449, -0.181, 2.326]}
                scale={250.029}
            />
            <mesh
                geometry={nodes["PLATDORM_platform-A_0"].geometry}
                material={materials["platform-A"]}
                position={[-1373.723, 105.756, 537.287]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={35.814}
            />
            <mesh
                geometry={nodes["MERD��VEN_wood-stair_0"].geometry}
                material={materials["wood-stair"]}
                position={[-1373.723, 105.756, 537.287]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={35.814}
            />
            <mesh
                geometry={nodes["L001_platform-pl_0"].geometry}
                material={materials["platform-pl"]}
                position={[-1373.723, 105.756, 537.287]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={35.814}
            />
            <mesh
                geometry={nodes["MERD��VEN001_wood-stair_0"].geometry}
                material={materials["wood-stair"]}
                position={[-401.52, -55.659, 901.118]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={35.814}
            />
            <mesh
                geometry={nodes["MERD��VEN002_wood-stair_0"].geometry}
                material={materials["wood-stair"]}
                position={[-392.079, -55.659, 174.257]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={35.814}
            />
            <mesh
                geometry={nodes["MERD��VEN003_wood-stair_0"].geometry}
                material={materials["wood-stair"]}
                position={[-392.079, -256.143, -952.101]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={35.814}
            />
            <mesh
                geometry={nodes.Sphere_terrain_0.geometry}
                material={materials.terrain}
                position={[-784.285, -252.373, 86.749]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={1966.505}
            />
            <mesh
                geometry={nodes.Sphere001_sea_0.geometry}
                material={materials.material}
                position={[-863.109, -286.421, 63.525]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={1960.476}
            />
        </a.group>
    );
}

export default Platform;